SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
res = (SCREEN_WIDTH, SCREEN_HEIGHT)
JUMP_VELOCITY = 15
MAX_JUMP = 100

MENU_START_X = SCREEN_WIDTH/4
MENU_START_Y = SCREEN_HEIGHT/8

ARROW_HALF_HEIGHT = 33 #px
ARROW_HALF_WIDTH = 43 #px

GRAVITY = 1

GAME_CAPTION = 'Icy Tower Clone'
